import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/content/AuthProvide';
import Header from '@/components/ui/Layout/Header';
import ThemeContextProvider from '@/content/ThemeProvider';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import 'nprogress/nprogress.css';
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <AuthProvider>
          <AntdRegistry>
            <ThemeContextProvider>
              <main className='dark:bg-dark bg-[#F9FAFB]'>
                <Header />
                <NextTopLoader />
                {children}
              </main>
            </ThemeContextProvider>
          </AntdRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
